# http服务启动端口
port: 8899

proxyConfig:
  - desc: "订阅转换服务"
    paths: # URL中PATH 不包含参数 。 可以配置多个
      - "/sub"
      - "/version"
      - "/readconf"
      - "/updateconf"
      - "/getruleset"
      - "/getprofile"
      - "/qx-script"
      - "/qx-rewrite"
      - "/render"
      - "/convert"
      - "/getlocal"
    hosts: # 要并发访问的host
      - "https://sub.id9.cc"
      - "https://sub.xeton.dev"
      - "https://api.dler.io"
      - "https://sub.maoxiongnet.com"
    filter:
      limitQps: 4           # 限流器，每秒只允许limiterQps访问,超过就
      limitHosts: 3         # 如果hosts数量过多，则随机选limit个进行请求
      timeOut: 5000         # 超时时间 单位毫秒
      respHeader: # 要转发的响应头header，大小写敏感
        - "Server"
        - "server"